services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: fastfood
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastfood-network

  backend:
    build:
      dockerfile: Dockerfile
    container_name: fastfood-backend
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DOCKER: jdbc:postgresql://postgres:5432/fastfood
    networks:
      - fastfood-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  fastfood-network: