services:
  postgres:
    image: postgres:14
    container_name: fastfood-postgres
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastfood-network

volumes:
  postgres_data:

networks:
  fastfood-network:
    external: true