services:
  postgres:
    image: postgres:14
    container_name: fastfood-postgres
    environment:
      POSTGRES_DB: fastfood
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
