services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastfood-network

  backend:
    build:
      dockerfile: Dockerfile
    container_name: fastfood-backend
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DOCKER: jdbc:postgresql://postgres:${DATABASE_PORT}/${DATABASE}
    networks:
      - fastfood-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  fastfood-network: