spring:
  devtools:
    restart:
      enabled: true
  application:
    name: fastfood
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:postgres}:${DATABASE_PORT}/${DATABASE}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      cache:
        use_second_level_cache: false
      use_query_cache: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/DDL,classpath:db/DML
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
  api-docs:
    path: /v3/api-docs
    version: openapi_3_1
application-description: "FastFood é uma aplicação de gerenciamento de pedidos online para fast food, focada em rapidez e eficiência."
application-version: "1.0.1"