apiVersion: v1
kind: ConfigMap
metadata:
  name: fastfood-config
data:
  DATABASE: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_HOST: "fastfooddb.cnbozhjkauqd.us-east-1.rds.amazonaws.com"

---
apiVersion: v1
kind: Secret
metadata:
  name: fastfood-secret
type: Opaque
data:
  DATABASE_USER: "ZmFzdGZvb2Q="  # Base64 encoded "fastfood"
  DATABASE_PASSWORD: "VGVzdGUxMjM="  # Base64 encoded "Teste123"
