apiVersion: v1
kind: ConfigMap
metadata:
  name: fastfood-config
data:
  DATABASE: "fastfood_db"
  DATABASE_PORT: "5432"
  DATABASE_HOST: "postgres-service"

---
apiVersion: v1
kind: Secret
metadata:
  name: fastfood-secret
type: Opaque
data:
  DATABASE_USER: "ZmFzdGZvb2Q="  # Base64 encoded "fastfood"
  DATABASE_PASSWORD: "VGVzdGUxMjM="  # Base64 encoded "Teste123"
