apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-fastfood-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-fastfood-app
  template:
    metadata:
      labels:
        app: order-fastfood-app
    spec:
      containers:
        - name: order-fastfood
          image: 361598269712.dkr.ecr.us-east-1.amazonaws.com/tech-challenge-fastfood:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: order-fastfood-config
                  key: DATABASE_HOST

            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  name: order-fastfood-config
                  key: DATABASE

            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: order-fastfood-config
                  key: DATABASE_PORT

            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: order-fastfood-secret
                  key: DATABASE_USER

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-fastfood-secret
                  key: DATABASE_PASSWORD
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: order-fastfood-service
spec:
  type: LoadBalancer
  selector:
    app: order-fastfood-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-fastfood-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: fiap-soat-seventeen-fastfood-service.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: order-fastfood-service
                port:
                  number: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-fastfood-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-fastfood-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    k8s-app: metrics-server
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  template:
    metadata:
      labels:
        k8s-app: metrics-server
    spec:
      serviceAccountName: metrics-server
      volumes:
        - name: tmp-dir
          emptyDir: {}
      hostNetwork: true
      containers:
        - name: metrics-server
          image: k8s.gcr.io/metrics-server/metrics-server:v0.3.7
          imagePullPolicy: IfNotPresent
          args:
            - /metrics-server
            - --cert-dir=/tmp
            - --secure-port=4443
            - --kubelet-preferred-address-types=InternalIP
            - --kubelet-use-node-status-port
            - --kubelet-insecure-tls
          ports:
            - name: main-port
              containerPort: 4443
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - name: tmp-dir
              mountPath: /tmp
      nodeSelector:
        kubernetes.io/os: linux
