apiVersion: v1
kind: Secret
metadata:
  name: ngrok-secret
type: Opaque
stringData:
  NGROK_AUTHTOKEN: "2uarBqzIKCXaNeAn2czG6AG3MSz_47FBsAvonMsfcs9PpKHAN"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
        - name: ngrok
          image: ngrok/ngrok:latest
          args:
            - start
            - --config
            - /etc/ngrok/ngrok.yml
            - --log=stdout
            - fastfood
          env:
            - name: NGROK_AUTHTOKEN
              valueFrom:
                secretKeyRef:
                  name: ngrok-secret
                  key: NGROK_AUTHTOKEN
          volumeMounts:
            - name: ngrok-config
              mountPath: /etc/ngrok
      volumes:
        - name: ngrok-config
          configMap:
            name: ngrok-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ngrok-config
data:
  ngrok.yml: |
    version: 2
    authtoken: 2uarBqzIKCXaNeAn2czG6AG3MSz_47FBsAvonMsfcs9PpKHAN
    tunnels:
      fastfood:
        proto: http
        addr: ingress-nginx-controller.ingress-nginx:80
        host_header: springboot.local.com
